apply from: 'gradle/scripts/helpers.gradle'

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name 'CleanroomMC CurseMaven'
                url 'https://curse.cleanroommc.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
    mavenLocal()
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'

    // GregTech CE Unofficial
    implementation rfg.deobf("curse.maven:gregtech-ce-unnoficial-557242:5519022")
    // CodeChickenLib (required by GTCEu)
    implementation rfg.deobf("curse.maven:codechicken-lib-1-8-242818:2779848")
}

if (!configurations.shade.dependencies.empty) {
    tasks.named('reobfJar').configure {
        inputJar.set(tasks.named('shadowJar').flatMap({ it.archiveFile }))
    }
}

tasks.shadowJar {
    enabled = !project.configurations.shade.dependencies.empty
    archiveClassifier = 'uberdev'
    configurations = [ project.configurations.shade ]
}
